name: Node CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun i
      - name: Build TypeScript
        run: bun run build
      - name: Release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          COMMIT_ASSETS: dist
          GIT_AUTHOR_NAME: "Botwerkz"
          GIT_AUTHOR_EMAIL: "rdwz@users.noreply.github.com"
          GIT_COMMITTER_NAME: "Botwerkz"
          GIT_COMMITTER_EMAIL: "rdwz@users.noreply.github.com"
